name: Pull request validation

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: "./.github/workflows/reusable-build.yml"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
