name: Reusable workflow example

on:
  workflow_call:
    inputs:
      configuration:
        required: false
        type: string
        default: Release

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello"
